services:
  - type: web
    name: expenses-tracker-backend
    runtime: node
    buildCommand: rm -rf node_modules && npm install --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
